//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyDetails_WebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TransactionDBEntities : DbContext
    {
        public TransactionDBEntities()
            : base("name=TransactionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AccountDetails> tbl_AccountDetails { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<PolicyData> PolicyDatas { get; set; }
        public virtual DbSet<PolicyTransaction> PolicyTransactions { get; set; }
    
        public virtual ObjectResult<Proc_GetAccountTransactionDetails_Result> Proc_GetAccountTransactionDetails(Nullable<int> accountNo, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var accountNoParameter = accountNo.HasValue ?
                new ObjectParameter("AccountNo", accountNo) :
                new ObjectParameter("AccountNo", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetAccountTransactionDetails_Result>("Proc_GetAccountTransactionDetails", accountNoParameter, startDateParameter, endDateParameter);
        }
    }
}
