//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyDetails_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Department { get; set; }
        public Nullable<int> Emp_Salary { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditOn { get; set; }
    }
}
