//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyDetails_WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetails
    {
        public int DetailId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> EditOn { get; set; }
    
        public virtual tbl_OrderList tbl_OrderList { get; set; }
    }
}
